### ISSUE TITLE
Differences?

### ISSUE THREAD

**Issue by RichardScottOZ** [Jmevorach/New-Shepard#1]
HI Jacob,

What would you say the differences are from the first version?

**Comment by Jmevorach** [comment]
Hello Richard!

So there are a few differences between this and the first version.

1. I added a bunch of new functionality to the command line tool. Notably the "shepard deploy" command now creates infrastructure in the form of Cloudformation using CDK, deploys the code to ECR, and automatically creates a new profile in the CLI that has all the attributes of the newly created Cloudformation stack encoded into it so that most commands don't need you to specify too many arguments because they're automatically set for you. There's also a "shepard destroy" command you can use to entirely tear down a Cloudformation stack for a Shepard setup in a single command.
2. I took your (I felt very good) advice and made it so the don't assume flag is by default set to true.
3. Shepard is now primarily available as a python package so you can pip install it. When new releases are made in this repository they are automatically pushed as updates to PyPi. 
4. I changed the structure of the folders used to deploy to Shepard. Now when you point to a directory to deploy from Shepard looks for a subdirectory called "code" (which contains your docker code for a Shepard workflow; workflows written for the old Shepard should work just the same in this version)  and another subdirectory called "infrastructure" that contains the Python CDK code used to make your Shepard setup. For most of these you can just copy the "infrastructure" folder found in this repository (https://github.com/Jmevorach/New-Shepard/tree/main/infrastructure) to get started but I wanted to make it so users could edit the infrastructure in the form of Python code if they were ever so inclined. For an example of how this looks for a functional setup there's an example in Shepard-Setups here (https://github.com/Jmevorach/Shepard-Setups/tree/main/testing-setup).
5. All the infrastructure is written in Python AWS CDK and the main Shepard setup code can be found here (https://github.com/Jmevorach/New-Shepard/blob/main/infrastructure/shepard.py). To edit attributes for the cloudformation stack edit the cdk.json file in the "infrastructure" folder which can be found for the folder in this repository here (https://github.com/Jmevorach/New-Shepard/blob/main/infrastructure/cdk.json).
6. Added GPU support to the main worker container so if you end up selecting an instance type that has Nvidia GPUs your workflow code should be able to use them (see here for relevant code: https://github.com/Jmevorach/New-Shepard/blob/main/code/arbitrary_worker_code.py#L403).
7. Shepard-Setups now works as a sort of central hub where users can share folders that users can use to set up all the infrastructure and deploy all the code needed to run a specific workflow. If you don't specify a filepath when using the "shepard deploy" command but instead specify a directory name in Shepard-Setups, Shepard will automatically clone the Shepard-Setups repository and then build a Shepard setup using the contents of the folder in that repository you specify. A working example of how one could do this can be seen in the "Hello World" example in this repository found in the README here (https://github.com/Jmevorach/New-Shepard#hello-world-example).

**Comment by Jmevorach** [comment]
There are other differences but those are the ones that first came to my mind and I feel are some of the most important.

**Comment by RichardScottOZ** [comment]
Great, thanks for that level of detail!

**Comment by Jmevorach** [comment]
No problem; anytime! Happy to help :) .
